#!/usr/bin/env python3
"""
Copyleft🄯 sometimes in 2023 by Florian Bantner
Free as in Freesbie. Fly away and have fun.
"""

import os
import openai
import argparse

Version = "0.9.0"

if __name__ == "__main__":

    argp = argparse.ArgumentParser(
            description="Your friendly Paintress V" + str( Version ) )
    argp.add_argument( "topic", type=str, nargs="+", help="use alternative topic" )
    args = argp.parse_args()

    file_path = os.path.realpath(__file__)
    key_file = os.path.join(os.path.dirname(file_path), "chatia.key")

    with open(key_file, "r") as f:
            api_key = f.read()
            openai.api_key = api_key.strip()

    response = openai.Image.create(
            prompt=" ".join( args.topic ),
            n=1,
            size="1024x1024" )

    print( response["data"][0]["url"] )

